
tasks:
  - before: bash <(curl https://gist.githubusercontent.com/Linkinlog/25b9e2c3ad360a50019d6dddb9b36f41/raw/6609d930ed3fc2d5ed4b1a166aa16c647c5b2049/install.sh)
  - name: aws-cli
    env:
      AWS_CLI_AUTO_PROMPT: on-partial
    init: |
      cd /workspace
      curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
      unzip awscliv2.zip
      sudo ./aws/install
      cd $THEIA_WORKSPACE_ROOT
vscode:
  extensions:
    - 42Crunch.vscode-openapi
